module.exports = {
  content: ['./src/**/*.{html,js,svelte,ts}'],
  theme: {
    extend: {}
  },
  plugins: [],
  safelist: [
    'text-2xl',
    'text-3xl',
        {
      pattern: /bg-(slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(50|100|200|300|400|500|600|700|800|900)/,
       variants: ['lg', 'hover', 'focus',  'disabled'],
    },
    {
      pattern: /(h|w)-(8|16|32)/,
    },
'border-2',
'border-gray-200',
'border-gray-500',      
'flex',
'flex-col',
'font-bold',
'form-checkbox',
'gap-1',
'grid',
'grid-cols-2',
'grid-flow-row',
'grid-rows-2',
'h-32',
'h-6',
'hidden',
'hover:border',
'hover:border-double',
'hover:border-gray-200',
'hover:outline-4',
'hover:shadow-md',
'invisible',
'items-center',
'justify-around',
'justify-center',
'leading-normal',
'm-1',
'm-2',
'mb-1',
'mr-1',
'mt-0',
'opacity-80',
'outline',
'outline-2',
'outline-black',
'outline-double',
'outline-offset-2',
'p-1',
'px-4',
'py-2',
'rounded-full',
'rounded-md',
'rounded-sm',
'shadow-cyan-500/50',
'shadow-md',
'shadow-sm',
'shadow-xl',
'space-x-2',
'text-gray-600',
'text-pink-200',
'text-sm',
'text-xl',
'uppercase',
'w-128',
'w-6',
'w-full',
'w-screen',
'disabled:border',
'disabled:border-slate-200',
'disabled:shadow-lg',
'disabled:text-slate-500'
]
};
